use_frameworks!

target 'GeneralToolsFramework_Example' do
  platform :ios, '11.0'

  pod 'GeneralToolsFramework', :path => '../'

  target 'GeneralToolsFramework_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.2.0'
    #pod 'Nimble', '~> 7.0.2'
    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

target 'GeneralToolsFramework Example Watch App' do
  platform :watchos, '7.0'

  pod 'GeneralToolsFramework', :path => '../'

end


target 'GeneralToolsFramework Example tvOS' do
  platform :tvos, '11.0'

  pod 'GeneralToolsFramework', :path => '../'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']) < Gem::Version.new('11.0')
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end
end
