use_frameworks!

target 'Example_iOS' do

  pod 'GeneralToolsFramework', :path => '../'

  target 'GeneralToolsFramework_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.2.0'
    #pod 'Nimble', '~> 7.0.2'
    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

target 'Example_tvOS' do

  pod 'GeneralToolsFramework', :path => '../'

end
