use_frameworks!

target 'GeneralToolsFramework_Example' do
  platform :ios, '9.0'

  pod 'GeneralToolsFramework', :path => '../'

  target 'GeneralToolsFramework_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.2.0'
    #pod 'Nimble', '~> 7.0.2'
    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

target 'GeneralToolsFramework Example Watch App' do
  platform :watchos, '6.3'

  pod 'GeneralToolsFramework', :path => '../'

end


target 'GeneralToolsFramework Example tvOS' do
  platform :tvos, '9.0'

  pod 'GeneralToolsFramework', :path => '../'

end
