variables:
  LANG: en_US.UTF-8

before_script:
  - pod repo update

stages:
  - build
  - test
  - lint
  - docs
  - deploy

build-pod:
  stage: build
  script:
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  tags:
    - xcode11

test:
  stage: test
  script:
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=latest" ONLY_ACTIVE_ARCH=NO | xcpretty -r junit
  tags:
    - xcode11
  artifacts:
    reports:
      junit: build/reports/junit.xml

cocoapods-lint:
  stage: lint
  script:
    - pod lib lint --allow-warnings
  tags:
    - xcode11

swiftlint:
  stage: lint
  script:
    - swiftlint
  tags:
    - xcode11

jazzy-docs:
  stage: docs
  script:
    - jazzy --podspec GeneralToolsFramework.podspec --output docs
  tags:
    - xcode11
  artifacts:
    paths:
      - docs

pages:
  dependencies:
    - jazzy-docs
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode11
  artifacts:
    paths:
      - public
