stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - pod repo update
  tags:
    - xcode

build:
  stage: build
  script:
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint
  tags:
    - xcode

pages:
  stage: deploy
  script:
    - jazzy --podspec GeneralToolsFramework.podspec --output public
  tags:
    - xcode
  artifacts:
    paths:
      - public
  allow_failure: true
