variables:
  LANG: en_US.UTF-8

stages:
  - build
  - test
  - lint
  - docs
  - deploy

build-ios:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - bundle exec fastlane ios buildios
  tags:
    - xcode15
  needs: []

build-tvos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - bundle exec fastlane tvos buildtvos
  tags:
    - xcode15
  needs: []

build-watchos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - bundle exec fastlane watchos buildwatchos
  tags:
    - xcode15
  needs: []

build-visionos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - bundle exec fastlane visionos buildvisionos
  tags:
    - xcode15
  needs: []

test:
  stage: test
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - bundle exec fastlane ios unittestios
  tags:
    - xcode15
  artifacts:
    paths:
      - fastlane/test-output/*
    reports:
      junit: fastlane/test-output/report.junit
  needs: []

cocoapods-lint:
  stage: lint
  script:
    - bundle install
    - bundle exec pod repo update
    - bundle exec pod lib lint --allow-warnings
  tags:
    - xcode15
  allow_failure: true
  needs: []

swiftlint:
  image: norionomura/swiftlint:0.45.1_swift-5.5.2
  stage: lint
  before_script: []
  script:
    - swiftlint lint
  allow_failure: true
  tags:
    - docker
  needs: []

jazzy-docs:
  stage: docs
  script:
    - bundle install
    - bundle exec jazzy --podspec GeneralToolsFramework.podspec --output docs
  tags:
    - xcode15
  allow_failure: true
  artifacts:
    paths:
      - docs
  needs: []

pages:
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode15
  allow_failure: true
  artifacts:
    paths:
      - public
  needs:
    - job: jazzy-docs
      artifacts: true
