variables:
  LANG: en_US.UTF-8

stages:
  - build
  - test
  - lint
  - docs
  - deploy

build-ios:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode15
  needs: []

build-tvos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-tvOS -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode15
  needs: []

build-watchos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-watchOS -sdk watchsimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode15
  needs: []

build-visionos:
  stage: build
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-visionOS -sdk xrsimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode15
  needs: []

test:
  stage: test
  script:
    - bundle install
    - cd Example/
    - bundle exec pod install --repo-update
    - cd ../
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty -r junit
  tags:
    - xcode15
  artifacts:
    paths:
      - build/reports/junit.xml
    reports:
      junit: build/reports/junit.xml
  needs: []

cocoapods-lint:
  stage: lint
  script:
    - bundle install
    - bundle exec pod repo update
    - bundle exec pod lib lint --allow-warnings
  tags:
    - xcode15
  allow_failure: true
  needs: []

swiftlint:
  image: norionomura/swiftlint:0.45.1_swift-5.5.2
  stage: lint
  before_script: []
  script:
    - swiftlint lint
  allow_failure: true
  tags:
    - docker
  needs: []

jazzy-docs:
  stage: docs
  script:
    - bundle install
    - bundle exec jazzy --podspec GeneralToolsFramework.podspec --output docs
  tags:
    - xcode15
  allow_failure: true
  artifacts:
    paths:
      - docs
  needs: []

pages:
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode15
  artifacts:
    paths:
      - public
  needs:
    - job: jazzy-docs
      artifacts: true
