stages:
  - setup
  - build

setup:
  stage: setup
  script:
    - pod repo update
  tags:
    - xcode

build:
  stage: build
  script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint
  tags:
    - xcode
