variables:
  LANG: en_US.UTF-8

stages:
  - build
  - test
  - lint
  - docs
  - deploy

build-ios:
  stage: build
  before_script:
    - bundle install
  script:
    - set -o pipefail && xcodebuild build -project GeneralToolsFramework.xcodeproj -scheme GeneralToolsFramework -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode13
  needs: []

build-tvos:
  stage: build
  before_script:
    - bundle install
  script:
    - set -o pipefail && xcodebuild build -project GeneralToolsFramework.xcodeproj -scheme GeneralToolsFramework -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
  tags:
    - xcode13
  needs: []

test:
  stage: test
  before_script:
    - bundle install
  script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project GeneralToolsFramework.xcodeproj -scheme GeneralToolsFrameworkTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest" ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty -r junit
  tags:
    - xcode13
  artifacts:
    paths:
      - build/reports/junit.xml
    reports:
      junit: build/reports/junit.xml
  needs: []

cocoapods-lint:
  stage: lint
  before_script:
    - bundle install
  script:
    - bundle exec pod lib lint --allow-warnings
  tags:
    - xcode13
  allow_failure: true
  needs: []

swiftlint:
  image: norionomura/swiftlint:0.45.1_swift-5.5.2
  stage: lint
  before_script: []
  script:
    - swiftlint lint
  allow_failure: true
  tags:
    - docker
  needs: []

jazzy-docs:
  stage: docs
  before_script:
    - bundle install
  script:
    - bundle exec jazzy --podspec GeneralToolsFramework.podspec --output docs
  tags:
    - xcode13
  artifacts:
    paths:
      - docs
  needs: []

pages:
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode13
  artifacts:
    paths:
      - public
  needs:
    - job: jazzy-docs
      artifacts: true
