variables:
  LANG: en_US.UTF-8

stages:
  - setup
  - build
  - test
  - lint
  - docs
  - deploy

setup:
  stage: setup
  script:
    - pod repo update
  tags:
    - xcode

build-pod:
  stage: build
  script:
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild build -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty
  tags:
    - xcode

test:
  stage: test
  script:
    - cd Example/
    - pod install
    - cd ../
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GeneralToolsFramework.xcworkspace -scheme GeneralToolsFramework-Example -sdk iphonesimulator12.2 -destination "platform=iOS Simulator,name=iPhone XS,OS=12.2" ONLY_ACTIVE_ARCH=NO | xcpretty -r junit
  tags:
    - xcode
  artifacts:
    reports:
      junit: build/reports/junit.xml

cocoapods-lint:
  stage: lint
  script:
    - pod lib lint --allow-warnings
  tags:
    - xcode

swiftlint:
  stage: lint
  script:
    - swiftlint
  tags:
    - xcode

jazzy-docs:
  stage: docs
  script:
    - jazzy --podspec GeneralToolsFramework.podspec --output docs
  tags:
    - xcode
  artifacts:
    paths:
      - docs

pages:
  dependencies:
    - jazzy-docs
  stage: deploy
  script:
    - mv docs/ public/
  tags:
    - xcode
  artifacts:
    paths:
      - public
